-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color7 = '#F8F8F2'
local Color16 = '#44475a'
local Color10 = '#9A86FD'
local Color15 = '#502935'
local Color1 = '#7F848E'
local Color3 = '#20E3B2'
local Color14 = '#0a3231'
local Color9 = '#FF6BCB'
local Color12 = '#f8f8f2'
local Color17 = '#6272a4'
local Color0 = '#FF5555'
local Color4 = '#FF79C6'
local Color5 = '#8BE9FD'
local Color13 = '#011627'
local Color2 = '#BD93F9'
local Color11 = '#2CCCFF'
local Color8 = '#EAC394'
local Color18 = '#00111d'
local Color6 = '#F1FA8C'

highlight('Error', nil, Color0, nil)
highlight('Comment', nil, Color1, nil)
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color4, nil)
highlight('Type', nil, Color5, 'italic')
highlight('String', nil, Color6, nil)
highlight('Identifier', nil, Color7, nil)
highlight('Function', nil, Color3, nil)
highlight('String', nil, Color8, nil)
highlight('Keyword', nil, Color9, nil)
highlight('Type', nil, Color9, nil)
highlight('Constant', nil, Color10, nil)
highlight('Type', nil, Color11, nil)
highlight('StatusLine', Color12, Color13, nil)
highlight('WildMenu', Color13, Color12, nil)
highlight('Pmenu', Color13, Color12, nil)
highlight('PmenuSel', Color12, Color13, nil)
highlight('PmenuThumb', Color13, Color12, nil)
highlight('DiffAdd', Color14, nil, nil)
highlight('DiffDelete', Color15, nil, nil)
highlight('Normal', Color13, Color12, nil)
highlight('Visual', Color16, nil, nil)
highlight('CursorLine', Color16, nil, nil)
highlight('ColorColumn', Color16, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color17, nil)
highlight('TabLine', Color18, Color17, nil)
highlight('TabLineSel', Color12, Color13, nil)
highlight('TabLineFill', Color18, Color17, nil)
highlight('TSPunctDelimiter', nil, Color12, nil)

link('TSRepeat', 'Repeat')
link('TSType', 'Type')
link('TSTagDelimiter', 'Type')
link('TSProperty', 'TSField')
link('NonText', 'Comment')
link('TSConstant', 'Constant')
link('TSFloat', 'Number')
link('TSKeyword', 'Keyword')
link('Conditional', 'Operator')
link('Repeat', 'Conditional')
link('TSString', 'String')
link('TSNumber', 'Number')
link('TSPunctBracket', 'MyTag')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Operator', 'Keyword')
link('CursorLineNr', 'Identifier')
link('TSOperator', 'Operator')
link('TelescopeNormal', 'Normal')
link('Macro', 'Function')
link('TSComment', 'Comment')
link('Folded', 'Comment')
link('TSConditional', 'Conditional')
link('Whitespace', 'Comment')
link('TSFuncMacro', 'Macro')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSTag', 'MyTag')
link('TSNamespace', 'TSType')
link('TSLabel', 'Type')
link('TSField', 'Constant')
link('TSParameter', 'Constant')
link('TSParameterReference', 'TSParameter')
link('TSFunction', 'Function')
