# tells tmux to use 24-bit color to override color change in tmux sessions
set-option -sa terminal-overrides ',xterm:Tc'

# add mouse support
set -g mouse on

# enable clipboard
set -g set-clipboard on

# change tmux prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Shift + Alt == M for window navigation key binding override
bind -n M-H previous-window
bind -n M-L next-window

# start window & pane indexing at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# set vi key mapping for copy mode
setw -g mode-keys vi
# change highlight to v
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# open panes in cwd
bind '"' split-window -v -c '#{pane_current_path}'
bind '%' split-window -h -c '#{pane_current_path}'

# bootstrap TPM if not exists
if "test ! -d ~/.config/tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm'"

# base plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# vim plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# theme plugins
source-file ~/.config/tmux/conf.d/dracula.conf

# tmux sessions are persistent
source-file ~/.config/tmux/conf.d/tmux-resurrect.conf
source-file ~/.config/tmux/conf.d/tmux-continuum.conf

run '~/.tmux/plugins/tpm/tpm'

