# load theme
set -g @plugin 'dracula/tmux'

# set up status bar/powerline
set -g @dracula-plugins 'spr battery time'
set -g @dracula-show-powerline true
set -g @dracula-transparent-powerline-bg true

# set colors
set -g @dracula-spr-colors "cyan dark_gray"
set -g @dracula-time-colors "light_purple dark_gray"

# set up left icon
set -g @dracula-show-left-icon "#{s|$HOME|~|:pane_current_path}"
set -g @dracula-show-left-sep 
set -g @dracula-show-right-sep 
set -g @dracula-inverse-divider  

# set up window status
set -g @dracula-show-flags false

# set up time
set -g @dracula-show-timezone false
set -g @dracula-time-format "%l:%M %p"

# set up battery
set -g @dracula-battery-label false
set -g @dracula-show-battery-status true

# set up spotify_player interface (add spr to plugins) 
set -g @dracula-spr-length 250

set -g @dracula-spr-play-icon " "
set -g @dracula-spr-pause-icon " "

set -g @dracula-spr-remote true
set -g @dracula-spr-remote-play-pause "P"

