# set up for tmux-resurrect, start tmux sessions with programs still running
set -g @plugin 'tmux-plugins/tmux-resurrect'

# set resurrected programs
set -g @resurrect-processes '"~nvim->nvim ." git vi vim man less more tail "~dlv" "~go" "~python3" "~pytest"'

# set resurrect directory
set -g @resurrect-dir '~/.config/tmux/resurrect'


