# Dracula theme
include dracula.conf

# Font
font_family      DM Mono Medium
font_size        16.0

# You can tweak this to fix your half-moon alignment!
modify_font cell_height 2px

# Terminal transparency
background_opacity 0.6
dynamic_background_opacity yes

# Shell
shell bash

# Misc
scrollback_lines 10000
enable_audio_bell no

